package com.juanma.firebaseexample.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

//Light colors
val primaryLight = Color(0xFF0E08A8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF5063FD)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF51599C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB5BCFF)
val onSecondaryContainerLight = Color(0xFF232B6C)
val tertiaryLight = Color(0xFF8C1199)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB743C2)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFBF8FF)
val onBackgroundLight = Color(0xFF1A1B24)
val surfaceLight = Color(0xFFFBF8FF)
val onSurfaceLight = Color(0xFF1A1B24)
val surfaceVariantLight = Color(0xFFE1E1F5)
val onSurfaceVariantLight = Color(0xFF454655)
val outlineLight = Color(0xFF757687)
val outlineVariantLight = Color(0xFFC5C5D8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3039)
val inverseOnSurfaceLight = Color(0xFFF1EFFC)
val inversePrimaryLight = Color(0xFFBCC2FF)
val surfaceDimLight = Color(0xFFDAD9E5)
val surfaceBrightLight = Color(0xFFFBF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FF)
val surfaceContainerLight = Color(0xFFEEECF9)
val surfaceContainerHighLight = Color(0xFFE9E7F4)
val surfaceContainerHighestLight = Color(0xFFE3E1EE)

// Dark colors
val primaryDark = Color(0xFFBCC2FF)
val onPrimaryDark = Color(0xFF00169D)
val primaryContainerDark = Color(0xFF475AF4)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFBCC2FF)
val onSecondaryDark = Color(0xFF21296A)
val secondaryContainerDark = Color(0xFF31397B)
val onSecondaryContainerDark = Color(0xFFCED1FF)
val tertiaryDark = Color(0xFFFEA9FF)
val onTertiaryDark = Color(0xFF580063)
val tertiaryContainerDark = Color(0xFFAD39B9)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12131B)
val onBackgroundDark = Color(0xFFE3E1EE)
val surfaceDark = Color(0xFF12131B)
val onSurfaceDark = Color(0xFFE3E1EE)
val surfaceVariantDark = Color(0xFF454655)
val onSurfaceVariantDark = Color(0xFFC5C5D8)
val outlineDark = Color(0xFF8F8FA1)
val outlineVariantDark = Color(0xFF454655)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1EE)
val inverseOnSurfaceDark = Color(0xFF2F3039)
val inversePrimaryDark = Color(0xFF3649E5)
val surfaceDimDark = Color(0xFF12131B)
val surfaceBrightDark = Color(0xFF383842)
val surfaceContainerLowestDark = Color(0xFF0D0E16)
val surfaceContainerLowDark = Color(0xFF1A1B24)
val surfaceContainerDark = Color(0xFF1E1F28)
val surfaceContainerHighDark = Color(0xFF292933)
val surfaceContainerHighestDark = Color(0xFF34343E)

//Background
val backgroundColorPrimary = Color(0xFF582FEB)
val backgroundColorSecondary = Color(0xFFBA8BE7)
val backgroundColor = Brush.verticalGradient(
    0.0f to backgroundColorPrimary,
    1000.0f to  backgroundColorSecondary
)